import Head from "next/head";
import Link from "next/link";
import { TbLocationFilled } from "react-icons/tb";
import { ImCheckmark2, ImPhone } from "react-icons/im";
import { SiGithub, SiLinkedin, SiGmail, SiFacebook } from "react-icons/si";
import IdCard from "@/components/about/IdCard";
import Hero from "@/components/about/Hero";
import Footer from "@/components/Footer";

export default function About() {
  const socialLinks = [
    {
      title: "Github",
      icon: <SiGithub />,
      link: "https://github.com/AbidHasanPiash",
    },
    {
      title: "LinkedIn",
      icon: <SiLinkedin />,
      link: "https://www.linkedin.com/in/abidhasanpiash/",
    },
    {
      title: "Gmail",
      icon: <SiGmail />,
      link: "mailto:mp.abidhasan@gmail.com",
    },
    {
      title: "Facebook",
      icon: <SiFacebook />,
      link: "https://www.facebook.com/meghpiash2",
    },
  ];
  return (
    <>
      <Head>
        <title>Abid Hasan | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="lg:max-w-7xl px-3 mx-auto pt-16">
        <Hero />
        <IdCard />
        <div className="mx-5 mt-10">
          <h2 className="lg:text-4xl text-3xl font-bold mb-4">Education.</h2>
          <p className="lg:text-2xl">
            Bachelor of Science, Computer Science and Engineering.
          </p>
          <p className="lg:text-2xl text-gray-500">
            Bangladesh Army University of Science & Technology (BAUST).
          </p>
          <p className="lg:text-lg text-sm">November 2016 - April 2021</p>
          <ul className="p-5 space-y-2">
            <li className="flex items-center justify-start space-x-3">
              <span>
                <ImCheckmark2 />
              </span>
              <span> Intensive course with core computer science topics.</span>
            </li>
            <li className="flex items-center justify-start space-x-3">
              <span>
                <ImCheckmark2 />
              </span>
              <span>
                C, C++, Java, Data Structures, Algorithms, OOP, DBMS.
              </span>
            </li>
            <li className="flex items-center justify-start space-x-3">
              <span>
                <ImCheckmark2 />
              </span>
              <span> Android application development.</span>
            </li>
            <li className="flex items-center justify-start space-x-3">
              <span>
                <ImCheckmark2 />
              </span>
              <span> Different software design patterns.</span>
            </li>
          </ul>
        </div>
        <Footer/>
      </div>
    </>
  );
}
