import Head from "next/head";
import Link from "next/link";
import { TbLocationFilled } from "react-icons/tb";
import { ImPhone } from "react-icons/im";
import { SiGithub, SiLinkedin, SiGmail, SiFacebook } from "react-icons/si";
import IdCard from "@/components/about/IdCard";
import Hero from "@/components/about/Hero";


export default function About() {
  const socialLinks = [
    {
      title: "Github",
      icon: <SiGithub />,
      link: "https://github.com/AbidHasanPiash",
    },
    {
      title: "LinkedIn",
      icon: <SiLinkedin />,
      link: "https://www.linkedin.com/in/abidhasanpiash/",
    },
    {
      title: "Gmail",
      icon: <SiGmail />,
      link: "mailto:mp.abidhasan@gmail.com",
    },
    {
      title: "Facebook",
      icon: <SiFacebook />,
      link: "https://www.facebook.com/meghpiash2",
    },
  ];
  return (
    <>
      <Head>
        <title>Abid Hasan | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="lg:max-w-7xl px-3 mx-auto mt-20 flex flex-col space-y-10 ">
        <Hero/>
        <IdCard/>
        <div>
          <div className="m-3 grid grid-cols-2">
            {/* About Me  */}
            <div className="my-5 mx-2 text-justify lg:col-span-1 col-span-2">
              <h2 className="lg:text-xl text-lg font-bold mb-4">About Me.</h2>
              <p className="mb-4 lg:text-md text-sm">
                Hi there! My name is Abid Hasan and I am a frontend developer. I
                have a year of experience working with web technologies,
                including HTML, CSS, React js, Next js and Tailwind CSS.
              </p>
              <p className="mb-4 lg:text-md text-sm">
                I am passionate about creating intuitive, user-friendly web
                experiences that make peoples lives easier. In my free time, I
                enjoy exploring new technologies, reading tech blogs, and
                building side projects to practice my skills.
              </p>
              <div>
                <div className="flex items-center justify-start space-x-3">
                  <TbLocationFilled />
                  <p>Banasree, Rampura, Dhaka-1219</p>
                </div>
                <div className="flex items-center justify-start space-x-3">
                  <ImPhone />
                  <Link href={"tel:01789507895"}>
                    <p>01789507895</p>
                  </Link>
                </div>
              </div>
            </div>
          </div>
          {/* Download Resume button */}
          <button
            className="w-fit mx-auto font-extralight text-purple-400 border-2 border-purple-500 px-2 py-1 rounded-full select-none
            hover:shadow-neon hover:bg-purple-500 hover:text-white hover:font-extrabold hover:shadow-purple-500"
          >
            Download Resume
          </button>
          {/* social media */}
          <div className="flex flex-col items-center justify-center">
            <h1>Please checkout my Social links.</h1>
            <div className="p-3 flex space-x-5">
              {socialLinks.map((social, index) => (
                <Link href={social.link} target="_blank" key={index}>
                  <div className="group lg:text-3xl text-2xl inline-flex items-center justify-center space-x-2 hover:text-purple-500 cursor-pointer">
                    {social.icon}
                    <span className="scale-0 text-[0px] lg:group-hover:text-2xl group-hover:scale-100 duration-200">
                      {social.title}
                    </span>
                  </div>
                </Link>
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
