import Head from 'next/head'
import Image from 'next/image';
import ProfilePicture from '../public/image/profile.png'
import {RiCloseFill} from 'react-icons/ri';
import {SiReact, SiNodedotjs, SiHtml5, SiCss3, SiJavascript, SiTailwindcss, SiFirebase, SiGithub, SiJira, SiCanva} from 'react-icons/si';
import {FiSquare, FiMinus} from 'react-icons/fi';
import TextWithColor from '@/components/TextWithColor';
import VanillaTilt from 'vanilla-tilt';
import React, {useEffect} from 'react';

export default function Home() {
  useEffect(() => {
    VanillaTilt.init(document.querySelector("#profile"), {
      max: 25,
      speed: 400,
      glare: true,
      "max-glare": 1,
    });
  }, []);
  return (
    <>
      <Head>
        <title>Abid Hasan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='lg:max-w-7xl lg:mx-auto mx-3 grid grid-cols-2 gap-4 mb-5 select-none'>
          {/* Profile picture */}
          <div id='profile' className='tilt-container col-span-2 lg:col-span-1 lg:w-96 w-full my-4 flex flex-col overflow-hidden rounded-xl ring-1 ring-purple-900 shadow-2xl shadow-purple-500'>
            <div className='flex items-center justify-between py-2 px-4 text-xl border-b border-slate-600'>
              <h1>Abid Hasan.</h1>
              <div className='flex items-center justify-center space-x-3'>
                  <FiMinus size={15}/>
                  <FiSquare size={15}/>
                  <RiCloseFill size={20}/>
              </div>
            </div>
            <Image 
              src={ProfilePicture} 
              priority
              draggable="false"
              alt="ProfilePicture"
              className='mx-auto object-cover select-none lg:hover:scale-110 duration-300 transform z-20'
            />
          </div>
          {/* Text about me */}
          <TextWithColor/>
          {/* My Expertise  */}
          <div className='col-start-1 col-span-2 lg:col-start-2 h-full w-full mt-4 flex flex-col rounded-xl ring-1 ring-purple-900 shadow-2xl shadow-purple-500 hover:scale-105 duration-200'>
            <div className='flex items-center justify-between py-2 px-4 lg:text-xl border-b border-slate-600'>
              <h1>My Expertise.</h1>
              <div className='flex items-center justify-center space-x-3'>
                  <FiMinus size={15}/>
                  <FiSquare size={15}/>
                  <RiCloseFill size={20}/>
              </div>
            </div>
            <div className='p-3 space-y-5 lg:text-xl'>
              <div className='flex items-center justify-between'>
                <h1>Frontend</h1>
                <div className='flex items-center justify-center space-x-3'>
                  <SiReact size={25}/>
                  <SiJavascript size={25}/>
                  <SiTailwindcss size={25}/>
                  <SiHtml5 size={25}/>
                  <SiCss3 size={25}/>
                </div>
              </div>
              <div className='flex items-center justify-between'>
                <h1>Backend</h1>
                <div className='flex items-center justify-center space-x-3'>
                  <SiNodedotjs size={25}/>
                </div>
              </div>
              <div className='flex items-center justify-between'>
                <h1>Tools</h1>
                <div className='flex items-center justify-center space-x-3'>
                  <SiFirebase size={25}/>
                  <SiGithub size={25}/>
                  <SiJira size={25}/>
                  <SiCanva size={25}/>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
