import Head from 'next/head'
import BtnTwoSideGlow from '@/components/common/BtnTwoSideGlow'
import Image from 'next/image'
import profile from '../public//image/profile.png'
import Stamp from '@/components/common/Stamp';
export default function Home() {
  return (
    <>
      <Head>
        <title>Abid Hasan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='lg:max-w-7xl lg:mx-auto mx-3 mt-20'>
        <div className='h-[550px] w-[1125px] grid grid-cols-2 mx-auto'>
          <div className='flex flex-col items-start justify-center space-y-4'>
            <h1 className='text-5xl font-extrabold'>The Web Designer That You Were Waiting For,</h1>
            <p>Hi, I create degital products over the internet.</p>
            <BtnTwoSideGlow text='Get Started'/>
          </div>
          <div className='relative border border-gray-700 rounded-full'>
            <div className='absolute translate-x-[70%] translate-y-[30%] flex items-center justify-center rotate-12 w-72 h-80 
              bg-[radial-gradient(ellipse_at_right,_var(--tw-gradient-stops))] from-sky-400 to-indigo-900 rounded-xl overflow-hidden'>
            </div>
            <div className='absolute translate-x-[35%] translate-y-[40%] -rotate-3 w-72 h-80 rounded-xl overflow-hidden'>
              <div className='w-full h-full relative flex items-end bg-gradient-to-r from-violet-200 to-pink-200'>
                <div className='w-60 h-60 absolute bottom-5 left-6 bg-gradient-to-r from-fuchsia-500 to-purple-500 rounded-full shadow-5xl'/>
                <Image src={profile} alt='profile' className='z-10'/>
              </div>
            </div>
            <div className='w-fit h-fit absolute top-20 left-10 rounded-full border-dotted border-[#c0f] bg-white/70 backdrop-blur-sm'>
              <Stamp text='Creative Developer.'/>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
