import Head from "next/head";
import Tiltcard from "@/components/portfolio/Tiltcard";
import { SwiperComponent } from "@/components/portfolio/Swiper";

export default function Works() {
  return (
    <>
      <Head>
        <title>Abid Hasan | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* ============Webapps=========== */}
        <div className="lg:h-fit lg:max-w-7xl lg:mx-auto mx-3 my-20 bg-[#0f172a]">
          <div className="relative h-full text-white/80">
            <div className="absolute z-0 lg:w-32 lg:h-32 w-36 h-36 animate-spin-slow top-1/4 lg:left-28 left-0 bg-opacity-20 bg-gradient-to-r from-blue-900 to-purple-700 rounded-full"/>
            <div className="absolute z-0 lg:w-60 lg:h-60 w-44 h-44 animate-spin-slow bottom-0 right-1/2 bg-opacity-20 bg-gradient-to-r from-rose-500 to-purple-500 rounded-full"/>
            <div className="absolute z-0 lg:w-40 lg:h-40 w-36 h-36 animate-spin-slow top-1/3 lg:right-20 right-0 bg-opacity-20 bg-gradient-to-r from-emerald-700 to-cyan-500 rounded-full"/>
            <h1 className="text-2xl text-center font-bold my-10">
              Some of my Web Applications.
            </h1>
            <div className="relative grid grid-cols-1 lg:grid-cols-2 gap-3">
              <Tiltcard />
              <Tiltcard />
            </div>
          </div>
        </div>
        {/* ============Extra text=========== */}
        <div className="lg:max-w-7xl lg:mx-auto mx-3">
          <div className="flex flex-col items-center justify-center">
            <div className="text-center">
              <h1 className="lg:text-4xl text-lg font-bold">
                &quot;<span className="lg:text-7xl text-2xl">Art</span> is not
                what you see,
                <br />
                but what you <span className="lg:text-7xl text-2xl">
                  make
                </span>{" "}
                others see.&quot;
              </h1>
              <p className="text-right mt-4">- Edgar Degas</p>
              <div className="absolute top-1/2 inset-x-1/2 z-0 lg:w-40 lg:h-40 w-36 h-36 animate-spin-slow bg-opacity-20 bg-gradient-to-r from-emerald-700 to-cyan-500 rounded-full"></div>
            </div>
          </div>
        </div>
        {/* ============Website=========== */}
        <div className="lg:max-w-7xl lg:mx-auto mx-3 my-20">
          <h1 className="text-2xl text-center font-bold my-10">
            Showcasing My Front-End Craftsmanship
          </h1>
          <div>
            <SwiperComponent />
          </div>
        </div>
      </div>
    </>
  );
}
